apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      volumes:
        - name: common-disk
          emptyDir: {}
      initContainers:
        - name: busybox
          image: busybox
          volumeMounts:
            - name: common-disk
              mountPath: /web-files
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo '<h2>Init container added this line!</h2>' > /web-files/index.html && sleep 20
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: common-disk
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-server
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

