apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
  - apiGroups: [""]         # "" indica il core API group
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch"]
